number = 13
slug = "zoom-and-focus"
status = "completed"
description = "Ctrl-A 1-9, n, s, x, a, z."
role = "legacy"
context_files = []
created_at = "2026-08-28T09:20:27"
completed_at = "2026-08-28T13:45:25"
commits = ["1bda34556b6d406ef5fb1d6d498799077c6bdee4"]
